### ISSUE TITLE
neurotolge.ee needs HTTPS

### ISSUE THREAD

**Issue by Madis0** [fishel/kama#2]
Your site http://neurotolge.ee/ needs to use always-enforced encrypted connection. 

Easy way to get a free cert is with [Let's Encrypt](https://letsencrypt.org/getting-started/) or [Cloudflare](https://www.cloudflare.com/ssl/). Don't put people's (translation) data at risk!

**Comment by fishel** [comment]
Thanks, Madis -- we finally switched to HTTPS
